### ISSUE TITLE
Errors in intepolate function when creating polar from raw data 

### ISSUE THREAD

**Issue by goliathuus** [hrosailing/hrosailing#10]
Hello, thanks for this awsome package 
I have had some trouble when reproducing the exemple, raising this error: 
![image](https://user-images.githubusercontent.com/44207554/160376485-ce81891e-b927-404f-91e0-e49999736664.png)
I think the error comes from the np.concatenate([point, interpolated_bsp]) that needs to be replaced by np.concatenate([point, [interpolated_bsp]]). 
interpolated_bsp is a float and point a list. 
Changing this appears to work fine

**Comment by rubbinduck** [comment]
Hello, thanks for pointing out this error. We must have missed this somehow...

It should be fixed now in the repo. The pypi-Version will be updated probably at the end of the week. 
If you find any more issues, please keep us updated!
