### ISSUE TITLE
Inconsistent documentation for the parameter `ws` of multiple methods from `PolarDiagramCurve` and `PolarDiagramPointcloud`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#100]
**Describe the bug**
For the parameter `ws` the first option (tuple of 2 int/float values) is inconsistent for `PolarDiagramCurve` and `PolarDiagramPointcloud` since they both work the same but are described differently in the documentation. That is the case for the methods `get_slices()`, `plot_polar()`, `plot_flat()` and `plot_convex_hull()`.

**Additional context**
Documentation for `PolarDiagramCurve`:
```
ws (tuple of length 2, iterable, int or float, optional): Slices of the polar diagram given as either

- a tuple of length 2, specifying an interval of considered wind speeds. The amount of slices taken from that interval are determined by the parameter n_steps,
```

Documentation for `PolarDiagramPointcloud`:
```
ws (See below, optional): Slices of the polar diagram given as either

- a tuple of 2 int/float values, which will be turned into the iterable numpy.linspace(ws[0], ws[1], n_steps) of int/float values. The iterable will then be interpreted as below,
```

**Comment by RobertSchueler** [comment]
Since 0.10.1 there is only one documentation for ws
