### ISSUE TITLE
Confusing documentation for the parameter `ws` of multiple methods from `PolarDiagramPointcloud`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#101]
**Describe the bug**
The last sentence of the documentation of the first option of the parameter `ws` (tuple of 2 int/float values) is confusing. The sentence `The iterable will then be interpreted as below` refers to the following note for `ws` but it could also be interpreted as though the iterable itself will be further described somewhere below. This issue occurs for the methods `get_slices()`, `plot_polar()`, `plot_flat()` and `plot_convex_hull()`.

**Comment by RobertSchueler** [comment]
This sentence does no longer exist in version 0.10.1
