### ISSUE TITLE
First side of documentation

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#11]
**Describe the bug**
The first side of the documentation doesn't correspond to the Docstring Style guide:

The first sentence of the page isn't complete yet.
Some Sections aren't formulated (i.e. "Getting Started").
The punctuation style isn't unified within the descriptions of the submodules. (some have a punctuation mark at the end and some don't)

**Comment by RobertSchueler** [comment]
Please check that this issue has been solved and that there are no further issues.
If that is the case, please close this issue.
If that is not the case, please elaborate.
