### ISSUE TITLE
`convex_directions` does not give meaningful results for port-side into-the-wind angles ( < 360) for table-based polar diagrams

### ISSUE THREAD

**Issue by ptr-rennstoff** [hrosailing/hrosailing#115]
**Describe the bug**
`convex_directions` does not give results for port-side close-reach angles ( < 360) for table-based polar diagrams

**To Reproduce / Minimal Example**
```
    import numpy as np
    import hrosailing.polardiagram as pol
    import hrosailing.cruising as cru

    pd = pol.from_csv("orc_format_example.csv", fmt="orc")
    pd = pd.symmetrize()

    directions = cru.convex_direction(pd, 5.0, 352.0)
    print(f"{directions}")

```

... results in ...

```
[Direction(angle=52.0, proportion=3.8846153846153846, sail=None), 
Direction(angle=308.0, proportion=-2.8846153846153846, sail=None)]
```
(one of the `proportion` values is negative)

**Expected behavior**
Give proper (same) result as `directions = cru.convex_direction(pd, 5.0, 8.0)`:

```
[Direction(angle=52.0, proportion=0.5769230769230769, sail=None), 
Direction(angle=308.0, proportion=0.42307692307692313, sail=None)]
```
(`proportion` values are both positive and add up to `1.0`)

**Comment by ptr-rennstoff** [comment]
You are right, in the minimal example the order was wrong. I corrected the description above and updated the output (see proportion values).

So there are results, but they seem off.

**Comment by rubbinduck** [comment]
Should be fixed with the latest release, thanks to @RobertSchueler. You should also be able to update your local `hrosailing` version with pip.
