### ISSUE TITLE
Directions returned from `convex_directions` don't add up to requested angle

### ISSUE THREAD

**Issue by ptr-rennstoff** [hrosailing/hrosailing#116]
**Describe the bug**
When `convex_directions` returns two directions, and the angles and proportions of the two directions are added together as vectors, the resulting vector has sometimes a slightly different angle than the requested wind angle `direction` (when calling `convex_direction(pd, ws, direction, im: Optional[InfluenceModel] = None, influence_data: Optional[dict] = None) -> List[Direction]`.

Screenshot of an application visualizing the results for a requested `direction = 20.0`:
<img width="770" alt="image" src="https://github.com/user-attachments/assets/18be24a1-0958-49d3-8cfd-007d13f39f0a">

**To Reproduce / Minimal Example**

```
    import numpy as np
    import hrosailing.polardiagram as pol
    import hrosailing.cruising as cru

    pd = pol.from_csv("Material/hrosailing CSVs/orc_format_example.csv", fmt="orc")
    pd = pd.symmetrize()
    
    angle = 20.0
    directions = cru.convex_direction(pd, 8.0, angle)
```

Results in 

```
direction[0]:
angle = 52.0
proportion = 0.6923076923076923

direction[1]:
angle = 308.0
proprotion = 0.3076923076923077
```

When looking at the directions and drawing a parallelogram with lengths `a = directions[0].proportion` and `b = directions[1].proportion` and the angle between `a` and `b`, `alpha=2 * angle` (see drawing), the expected angle `gamma` would be the angle `alpha - angle` (angle of the parallelogram's diagonal to side `a`)

<img width="927" alt="image" src="https://github.com/user-attachments/assets/034ea63f-d33f-4bb6-b446-5c1b96a998b1">

With (my hopefully correct) calculations in the parallelogram with the given values from the directions example above results in a `angle = 26,21` (and not `20.0` as requested), which also corresponds to the findings in the visualization screenshot above.

The assumption is that the results of `convex_directions` are close, but not correct.

**Expected behavior**
The directions' proportions should build a parallelogram that has a diagonal with the same angle as the requested angle (see above).

**Comment by ptr-rennstoff** [comment]
One more finding: It seems like your metric for a solution in `convex_directions` is 

```
directions[0].angle * directions[0].proportion + directions[1].angle * directions[1].proportion = requested_wind_angle
```

but that is not the same as 

Sail to `directions[0].angle` for `directions[0].proportion` of the time, then to `directions[1].angle` for `directions[1].proportion` of the time.

Am I making the wrong assumptions what `convex_directions` should return?

**Comment by RobertSchueler** [comment]
Hi! Thank you a lot for reporting. I will need a quite moment to recall the matter and think about this issue. I will come back to you then

**Comment by RobertSchueler** [comment]
Thanks for reporting. Your expectations seem to be correct. I expect there is some misconception in the convex_direction method that needs to be fixed.

**Comment by rubbinduck** [comment]
Should be fixed, with the latest release, thanks to @RobertSchueler. You should be able to update your local version of `hrosailing` with pip now, too
