### ISSUE TITLE
Unclear documentation of parameters in class `polardiagramtable`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#13]
**Describe the bug**
In the class `polardiagramtable` from the module `PolarDiagram` the documentation of the parameters `ws_resolution` and `wa_resolution` is unclear. For the case that they are array_like, it seems as if a part of the line of the documentation is missing.

**Comment by RobertSchueler** [comment]
Please check that this issue has been solved and that there are no further issues.
If that is the case, please close this issue.
If that is not the case, please elaborate.

**Comment by Loitador41** [comment]
The notes that were added abbreviate 'numpy' to 'np' which is inconsistent to the rest of the documentation. I pushed the fixed version onto the branch `quality_check1` but the modification still needs to be added to the documentation document.

**Comment by rubbinduck** [comment]
Can you resolve the merge conflicts in `quality_check1` with `main`? Then we can deploy the changes

**Comment by Loitador41** [comment]
The conflicts should be resolved now.

**Comment by Loitador41** [comment]
I created the pull request.
