### ISSUE TITLE
Unclear documentation of the parameter `f` in class `PolarDiagramCurve`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#14]
**Describe the bug**
There seems to be a word missing in the description of the parameter `f` ( (...) where `ws`, `wa` and ? should be (...) ).

**Comment by RobertSchueler** [comment]
Please check that this issue has been solved and that there are no further issues.
If that is the case, please close this issue.
If that is not the case, please elaborate.
