### ISSUE TITLE
Unexpected behaviour when using `from_csv` with `curve_hro_format_example.csv`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#20]
**Describe the bug**
With published version of hrosailing:
When trying to use the function `from_csv` with `curve_hro_format_example.csv` as the first parameter, it is throwing the following error:
`IndexError: list index out of range`.

**Expected behavior**
It shouldn't throw the error.

**Comment by rubbinduck** [comment]
Fixed with commit 86db43f47b940ea1e839db321db606fce89ede19
