### ISSUE TITLE
Unexpected behaviour when using `from_csv` with `multisails_hro_format_example.csv`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#21]
**Describe the bug**
With published version of hrosailing:
When trying to use the function `from_csv` with `multisails_hro_format_example.csv` as the first parameter, it is throwing the following error:
`SyntaxError: unexpected EOF while parsing`.

**Expected behavior**
It shouldn't throw the error.

**Comment by rubbinduck** [comment]
(Hopefully ) Fixed with commit 0a98c49296e4cc574994c5c1db2a0f738b4e97fc
