### ISSUE TITLE
Unexpected behaviour when using `from_csv` with `cloud_hro_format_example.csv` or `multisails_hro_format_example.csv`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#23]
**Describe the bug**
With Gitversion of hrosailing:
When trying to use the function `from_csv` with `cloud_hro_format_example.csv` or `multisails_hro_format_example.csv` as the first parameter, it is throwing the following error:
`_csv.Error: Could not determine delimiter`.

**Expected behavior**
It shouldn't throw the error.

**Comment by rubbinduck** [comment]
Fixed with commit 34bea7bcca185475ff2ecbf8197f1bb571eb1992 and 3a3faf63c3a96fda3652c05234a596761bac3cde
