### ISSUE TITLE
Unexpected behaviour of `plot_color_gradient()` and `plot_flat()` from class `PolarDiagram`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#26]
**Describe the bug**
When trying to use the function `plot_color_gradient()` or `plot_flat()`, it is throwing the error `KeyError: 'rectlinear'` which is the direct cause of the following error: `ValueError: Unknown projection 'rectlinear'`.

**Expected behavior**
It shouldn't throw the error.

**Comment by rubbinduck** [comment]
Fixed with commit dcadcc41dd6714c86310d413e7ed31711a521826
