### ISSUE TITLE
Documentation of `PolarDiagramInitializationException` is missing

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#27]
**Describe the bug**
The exception `PolarDiagramInitializationException` isn't documented. Furthermore the description of the exception in the `Raises`-section is missing in the documentation of two classes within the module `polardiagram`, in `PolarDiagramCurve` and `PolarDiagramTable`.

**Comment by RobertSchueler** [comment]
Please check that this issue has been solved and that there are no further issues.
If that is the case, please close this issue.
If that is not the case, please elaborate.
