### ISSUE TITLE
Unclear documentation of the parameter `colors` in the methods `plot_convex_hull`, `plot_flat` and `plot_polar` from module `polardiagram`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#29]
**Describe the bug**
In some instances of the documentation of `colors` the option is given to pass a `(ws, color)` pair. However it isn't specified how exactly that is to be done.

**Additional context**
This problem is found in the documentation of the following methods:
- `plot_convex_hull` from the class `PolarDiagramCurve`
- `plot_flat` from the class `PolarDiagramCurve`
- `plot_polar` from the class `PolarDiagramCurve`
- `plot_flat` from the class `PolarDiagramMultiSails`
- `plot_polar` from the class `PolarDiagramMultiSails`
- `plot_convex_hull` from the class `PolarDiagramPointcloud`
- `plot_flat` from the class `PolarDiagramPointcloud`
- `plot_polar` from the class `PolarDiagramPointcloud`
- `plot_convex_hull` from the class `PolarDiagramTable`
- `plot_flat` from the class `PolarDiagramTable`
- `plot_polar` from the class `PolarDiagramTable`

**Comment by rubbinduck** [comment]
Since colors is expected to be a sequence, the format should be e.g a list or a tuple of tuples like
[(ws_1, color_1), (ws_2, color_2), ...]

**Comment by RobertSchueler** [comment]
Please check that this issue has been solved and that there are no further issues.
If that is the case, please close this issue.
If that is not the case, please elaborate.
