### ISSUE TITLE
Unexpected behaviour of `symmetrize()` from the class `PolarDiagramCurve` in connection with `plot_polar()`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#30]
**Describe the bug**
When trying to symmetrize a PolarDiagram and then plotting the symmetrized PolarDiagram with `plot_polar()`, it plots the normal version of the PolarDiagram.

**Expected behavior**
It should plot the now symmetrized (= mirrored at the 0° - 180° axis) PolarDiagram.

**Comment by rubbinduck** [comment]
Can you give a minimal example of your code?

**Comment by Loitador41** [comment]
I worked with `from_csv` which might have been the problem:

`pd = from_csv("curve_hro_format_example.csv", fmt="hro")
pd2 = pd.symmetrize()
pd2.plot_polar()`

**Comment by rubbinduck** [comment]
Fixed with commit fc2379b90eec8a17e39ed872fef3450a21eba2a2
