### ISSUE TITLE
Unclear documentation of parameter `range_` from `get_slices()` from `PolarDiagramPointCloud`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#39]
**Describe the bug**
The parameter `range_` doesn't seem to be used for the calculation of the slices.

**To Reproduce / Minimal Example**
```python
pd_csv = from_csv("cloud_hro_format_example.csv")
print(pd_csv.get_slices(16, range_=3))
```

**Expected behavior**
It should convert the given `w` in `ws` to the interval `(w - range_, w + range_)`.

**Additional context**
The output of the given example is simply the slice of `ws`=16.

**Comment by rubbinduck** [comment]
If i see it correctly, the point cloud in question doesn't contain any wind speeds in the interval `[13, 19]` other then `16`?

**Comment by rubbinduck** [comment]
Yes, it puts out the slice with the name `ws=16`, but with all points with wind speed in the interval `[13,19]` (in this case, all points with wind speed `14` and `16` ). That's how the function is supposed to behave

**Comment by RobertSchueler** [comment]
Changed title to "Unclear documentation" since the behaviour is correct but the documentation is missleading.
We should clarify what the terms 'slice' and 'interval' are supposed to mean in that context
