### ISSUE TITLE
Unexpected behaviour of `colors` in combination with `range_` from `plot_flat()` from `PolarDiagramPointcloud`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#41]
**Describe the bug**
The different slices are all colored in a single color.

**To Reproduce / Minimal Example**
```python
pd_csv = from_csv("cloud_hro_format_example.csv")
pd_csv.plot_flat(16, colors=('blue', 'red'), range_=2)
```

**Expected behavior**
It should color the slices in different colors, depending on which colors where specified.

**Additional context**
This problem also occurs when using `plot_polar()` from `PolarDiagramPointcloud`.

**Comment by rubbinduck** [comment]
Related to issue #39 you only get one slice, when you pass a single value, regardless of `range_`...

**Comment by RobertSchueler** [comment]
This issue comes from a missunderstanding, explained in detail in #39.
The behaviour is as intended. The misunderstanding should be prevented in the future by a better documentation, as commented in #39.
