### ISSUE TITLE
Unexpected behaviour of `convex_direction()` and `cruise()` from `hrosailing.cruising`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#53]
**Describe the bug**
When trying to use on of the two functions, it throws the following two errors:
`AttributeError: 'list' object has no attribute 'ravel'`
`AttributeError: attribute '__isabstractmethod__' of 'classmethod' objects is not writable`

**To Reproduce / Minimal Example**
```python
pd = from_csv("curve_hro_format_example.csv")
hrosailing.cruising.convex_direction(pd=pd, ws=15, direction=42)
```

**Additional context**
When using a `PolarDiagramTable` instance, it doesn't throw the first error.

It seems that the second error occurs when using any function from the subclasses of `PolarDiagram`.

**Comment by RobertSchueler** [comment]
While trying to replicate the ```AttributeError: attribute '__isabstractmethod__' of 'classmethod' objects is not writable``` I stumbled upon another issue (#58). I postpone the remaining work towards fixing this issue until #58 is fixed.

**Comment by RobertSchueler** [comment]
#58 is fixed now, but I can not replicate the AttributeError.

Can you please check again if this issue still occurs on your machine?

**Comment by Loitador41** [comment]
The second AttributeError doesn't occur anymore but the error `'list' object has no attribute 'ravel'` still occurs.

**Comment by RobertSchueler** [comment]
I still can not reproduce the first Error. Could you please comment the full Error stack?
(You can remove everything related to your private file system).

**Comment by RobertSchueler** [comment]
Oh, nevermind. I can reproduce the Error using cruise instead of convex_direction

**Comment by Loitador41** [comment]
The errors above have been solved but when using a multisail polar diagram it now throws the following error:
`IndexError: list index out of range`
