### ISSUE TITLE
Unexpected behaviour of the plotting functions from `PolarDiagramMultiSails`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#61]
**Describe the bug**
The plots of the different sails overlap so that only one of the plots is visible.

**To Reproduce / Minimal Example**
```python
pd_tbl1 = tbl([42, 44, 46], [21, 42, 84], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pd_tbl2 = tbl([42, 44, 46], [21, 42, 84], [[10, 11, 12], [13, 14, 15], [16, 17, 18]])
pd_mts = mts((pd_tbl1, pd_tbl2), ("Sail 1", "Sail 2"))
pd_mts.plot_flat()
```

**Expected behavior**
One should be able to see all of the plots.

**Comment by Loitador41** [comment]
The same issue occurs when trying to plot two polar diagrams of boats with one sail per boat.

**Comment by RobertSchueler** [comment]
Plotting two polar diagrams works as intended.
You need to plot both on the same axis for the exspected result, not on seperate axis which overlay.

For example:

```
from hrosailing.polardiagram import PolarDiagramTable as tbl
import matplotlib.pyplot as plt

pd_tbl1 = tbl([42, 44, 46], [21, 42, 84], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pd_tbl2 = tbl([42, 44, 46], [21, 42, 84], [[10, 11, 12], [13, 14, 15], [16, 17, 18]])

ax = plt.subplot(111)

pd_tbl1.plot_flat(ax=ax)
pd_tbl2.plot_flat(ax=ax)

plt.show()
```
