### ISSUE TITLE
PolarDiagramPointcloud.polar_plot crashes when called empty

### ISSUE THREAD

**Issue by RobertSchueler** [hrosailing/hrosailing#7]
**Describe the bug**
When calling the polar_plot method without any further input on a sparse PolarDiagramPointcloud it raises a PolarDiagramException.

```
import hrosailing.polardiagram as pol
import matplotlib.pyplot as plt

pts = [[6,52,3.72], [6,135,3.77],[12,110,5.99], [14, 52, 5.5]]
pd = pol.PolarDiagramPointcloud(pts=pts)

pd.plot_polar()
plt.show()
```

**Expected behavior**
Should show a plot containing all points of the polar diagram. Instead it raises 

```
hrosailing.polardiagram.PolarDiagramException: No points with wind speed in range (6.142857142857142, 8.142857142857142) found
```

**Comment by rubbinduck** [comment]
Fixed with commit c5389850598d51c988f9a891d684f14e48af8e2b
