### ISSUE TITLE
Unexpected behaviour of the plotting functions from `PolarDiagramMultiSails` when using `colors` incorrectly

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#80]
**Describe the bug**
When trying to give `colors` a single color without putting it in brackets, the plotting function tries to interpret each letter as a color.

**To Reproduce / Minimal Example**
```python
import matplotlib.pyplot as plt
from hrosailing.polardiagram import PolarDiagramMultiSails as mts
from hrosailing.polardiagram import PolarDiagramTable as tbl

pd_tbl1 = tbl([42, 44, 46], [21, 42, 84], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pd_tbl2 = tbl([42, 44, 46], [21, 42, 84], [[10, 11, 12], [13, 14, 15], [16, 17, 18]])
pd_mts = mts((pd_tbl1, pd_tbl2), ("Sail 1", "Sail 2"))

pd_mts.plot_flat((40,45), colors='green', show_legend=True)

plt.show()
```

**Expected behavior**
It would make more sense to throw a SyntaxError.

**Additional context**
In the example above 'g' would be interpreted as the color 'green' and 'r' would be interpreted as the color 'red'. This is shown in the legend of the plot.

**Comment by RobertSchueler** [comment]
This issue also appears for the other polar diagram types.

Furthermore, the legend and the plot seem to differ (legend shows red and green while plot is green only).
When using `colors="gr"` instead, it works equivalent to `colors=["green", "red"]`.
On the other hand `colors=["green", "red", "e", "e", "n"]` works as intended.

**Comment by RobertSchueler** [comment]
Now it should take a color_like or a sequence as usual.

A string is interpreted as a single color if it is a valid color string (then this color is used for every slice) or as a sequence otherwise. So, something like "grb" as a short-hand should also work.

I changed the documentation accordingly
