### ISSUE TITLE
Documentation of `OutsideGridException` from `hrosailing.cruising` missing for `isochrone()`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#81]
**Describe the bug**
The function `isochrone()` throws the exception ``hrosailing.cruising.OutsideGridException: `point` is outside the grid. Weather data not available.`` which is not written down in the documentation.

**Comment by RobertSchueler** [comment]
This is intended. The `OutsideGridException` is thrown by the used instance of `WeatherModel` and not directly by isochrone.
One could use a `WeatherModel` that does not throw this exception and `isochrone()` would also work without this exception.
