### ISSUE TITLE
Unexpected `OutsideGridException` thrown using `cost_cruise()` from `hrosailing.cruising` on `PolarDiagramCurve`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#91]
**Describe the bug**
When trying to use `cost_cruise()` with an instance of `PolarDiagramCurve`, the following error is thrown:
`hrosailing.cruising.OutsideGridException: `point` is outside the grid. Weather data not available`.

**To Reproduce / Minimal Example**
```python
from hrosailing.cruising import cost_cruise
from hrosailing.cruising import WeatherModel
from hrosailing.polardiagram import from_csv
import numpy as np
from datetime import timedelta
from datetime import datetime as dt

n, m, k, l = 500, 50, 40, 3

data = 20 * (np.random.random((n, m, k, l)) - 0.5)

wm = WeatherModel(
    data=data,
    times=[dt.now() + i * timedelta(hours=1) for i in range(n)],
    lats=np.linspace(40, 50, m),
    lons=np.linspace(40, 50, k),
    attrs=["UGRID", "VGRID", "TMP"]
)

pd = from_csv("../../examples/csv-format-examples/curve_hro_format_example.csv")
print(cost_cruise(pd=pd, start=(42, 42), end=(45, 45), start_time=dt.now(), wm=wm))
```

**Comment by Loitador41** [comment]
Now sometimes the error is still thrown and sometimes it works fine. I tried to run the same code multiple times and it still throws the error from time to time.

**Comment by RobertSchueler** [comment]
The initial value problem solver keeps checking unrealistic points in time yielding these issues.

For now, I will use a dirty fix, setting a very low boat speed (1/1000 knots) on places in grid where the weather is unknown. Maybe we can think of a more sophisticated way in the future.
